### ISSUE TITLE
CSS import compile error in NextJS app

### ISSUE THREAD

**Issue by arunmenon1975** [jrebecchi/React-Web-Media-Player#10]
I get the following compile error when i tried a  to use the package in a NextJS project :

```
Failed to compile
./node_modules/react-web-media-player/es/components/Container.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-web-media-player/es/components/Container.js
This error occurred during the build process and can only be dismissed by fixing the error.
```
NextJS has this limitation and actually requires that global CSS imports are done in a special file (_app.tsx) or via directives  in a special `<Head>` component that can have a `<link rel="stylesheet" ...>`(like `rect-helmet`) in normal files.

**Comment by jrebecchi** [comment]
Hi,

I think this is a NextJS related issue. I found this solution on stackoverflow:
[https://stackoverflow.com/questions/45192088/import-css-files-from-node-modules-in-next-js](https://stackoverflow.com/questions/45192088/import-css-files-from-node-modules-in-next-js).

Is it working for you ?

**Comment by arunmenon1975** [comment]
I re-installed and tried the following options:

- Use Next's `dynamic` module with `{ssr: false}`. This solutions worked whenever i encountered SSR-specific issues (mostly related to calling DOM-related methods and properties without checks)
- call `import 'react-web-media-player/es/components/Container.css'` inside `_app.tsx`. This is the recommended approach for several popular packages like `react-modal`, `react-toastify` and a bunch of others.

It didn't work. I guess now i have 2 options available:

- modify `next.config.js` for webpack-specific fixes. Im not too keen since modifying the core slightly increases the chances of bugs or issues.  Modifying and extending the config is quite a common activity but i am just weighing the risk-benefit ratio vis-a-vis future updates, upgrading, passing on the codebase etc
- install `@webdeb/next-styles` and add it to `next.config.js`. I am again hesitant because it would be over-riding the fixes nextjs already has for similar issues. [This RFC](https://github.com/vercel/next.js/issues/8626) goes into detail and the consensus fix has shipped since v9.2

i am ok with closing the issue since there are work-arounds/fixes and probably i just might opt for one of them.

**Comment by arunmenon1975** [comment]
Closing the issue since there are workarounds

**Comment by jrebecchi** [comment]
Hi again,

Indeed next.js allows styles imports from node_modules :
[https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules](https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules)

Using the UMD version would it work ? 
```
import 'react-web-media-player/umd/react-web-media-player.js'
import 'react-web-media-player/umd/main.011bfcd5.css'
```

Btw, thanks a lot for this positive feedback! A little start is welcome if you can finally use it :). About YouTube, if you find a way to get the YouTube URL of the video file you can pass it to React-Web-Media-Player.

**Comment by arunmenon1975** [comment]
I tried and looks like it doesn't work. There were no compile errors though so the import goes through fine. I did get one error but that was regarding `window` being undefined  which i fixed with:

```
const MediaPlayer = dynamic(() => import('./MediaPlayer'), {
  ssr: false
});
```

Main page where the video is called: 

```
...
<MediaPlayer />
...
```


In MediaPlayer file:

```
import React, { useEffect, useRef } from 'react';
import 'react-web-media-player/umd/react-web-media-player.js'
import 'react-web-media-player/umd/main.011bfcd5.css'

 
const MediaPlayer = () => {
 let ReactWebMediaPlayer;
  useEffect(()=>{
    if((window as any).ReactWebMediaPlayer){
      ReactWebMediaPlayer = (window as any).ReactWebMediaPlayer
    }
  },[(window as any).ReactWebMediaPlayer])

  if(!ReactWebMediaPlayer){
    return null
  }


  return (
    <ReactWebMediaPlayer
        title="My own video player"
        video="vide-file-path" 
        thumbnail="thumbnail-path"
    />
  )
}

export default MediaPlayer;
```

I expected to see `ReactWebMediaPlayer` attached to the  `window` object but it doesn't seem to get populated.

**Comment by arunmenon1975** [comment]
**UPDATE** 

Importing via `import ReactWebMediaPlayer from 'react-web-media-player/umd/react-web-media-player.js' seems to work
`

So this works:

```
import React, { useEffect, useRef } from 'react';
import ReactWebMediaPlayer from  'react-web-media-player/umd/react-web-media-player.js'
import 'react-web-media-player/umd/main.011bfcd5.css'

 
const MediaPlayer = () => {

  return (
    <ReactWebMediaPlayer
        title="My own video player"
        video="vide-file-path" 
        thumbnail="thumbnail-path"
    />
  )
}

export default MediaPlayer;

```

**Comment by jrebecchi** [comment]
Great ! If someone else encounters the problem he will have the recipe 👨‍🍳 .
