### ISSUE TITLE
Images in a Slideshow not Centred in Player

### ISSUE THREAD

**Issue by Azazi** [jrebecchi/React-Web-Media-Player#12]
When using the player to display a slideshow, the images are not always centred. This is due to a simple bug in `react-web-media-player/lib/components/Medias/Channels/Slideshow.js` L173:

```
var margin = (height - imgHeight / imgWidth * width) / 2;
```

The lack of parentheses around the `height - imgHeight` & `imgWidth * width` calculations results in erroneous calculations for the `leftMargin` CSS property.  This is addressed in #11

**Comment by jrebecchi** [comment]
Thanks a lot for reporting this bug and fix. I look at that next week and will release a new version with your fix!
